/*
 * Copyright (c) 2024 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 11, 22 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 4.598740245868833, 3.0765670669068275, 2.0936788450296744 };
const float ei_classifier_anom_mean[3] = { 4.124793295218616, 2.8621887842689953, 2.2566755305631605 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { -0.8932446837425232, -0.9206010103225708, -1.0555535554885864 }, 0.44706442176280814 },
	{ ( float[3] ) { -0.18241189420223236, 1.3848332166671753, -0.047954872250556946 }, 0.4283016643402807 },
	{ ( float[3] ) { -0.45280012488365173, -0.04285679757595062, 1.1572307348251343 }, 0.48831520546448354 },
	{ ( float[3] ) { -0.5803501605987549, -0.3474550247192383, 1.3771454095840454 }, 0.4668091557202226 },
	{ ( float[3] ) { -0.3617682158946991, -0.2953453063964844, 2.139949083328247 }, 0.8487331400633397 },
	{ ( float[3] ) { 1.8497564792633057, 0.4633482098579407, 0.40470075607299805 }, 0.40506568512499164 },
	{ ( float[3] ) { -0.31090688705444336, -0.021115392446517944, 2.8780505657196045 }, 0.717046702007329 },
	{ ( float[3] ) { 1.3487802743911743, 0.05855249986052513, -0.3265905976295471 }, 0.45209716419573037 },
	{ ( float[3] ) { 1.242958903312683, -0.3643527626991272, -0.360481321811676 }, 0.5173822833267611 },
	{ ( float[3] ) { -0.6300982236862183, -0.2641720175743103, -0.6059874296188354 }, 0.33626096200131983 },
	{ ( float[3] ) { 2.127530336380005, -0.0813307911157608, 0.63042151927948 }, 0.30970543912743703 },
	{ ( float[3] ) { 1.5869358777999878, -0.18067899346351624, -0.47575247287750244 }, 0.40623197471751377 },
	{ ( float[3] ) { 1.9828072786331177, 0.13638727366924286, 0.23071718215942383 }, 0.40964539856009763 },
	{ ( float[3] ) { -0.6310456395149231, -0.3500349223613739, -0.8298218846321106 }, 0.37739739342951 },
	{ ( float[3] ) { 1.0710818767547607, -0.21958746016025543, 0.4647150933742523 }, 0.4479038173963703 },
	{ ( float[3] ) { -0.5006846189498901, 0.21102775633335114, -0.3571833074092865 }, 0.36028828016611 },
	{ ( float[3] ) { -0.688725471496582, -0.590067982673645, 0.9147701263427734 }, 0.5268324314376784 },
	{ ( float[3] ) { 0.036015503108501434, 0.597315788269043, 0.6806364059448242 }, 0.7051987527572872 },
	{ ( float[3] ) { -0.15625692903995514, 2.0199451446533203, 0.5861085057258606 }, 0.5923043331035976 },
	{ ( float[3] ) { -0.48890170454978943, 0.0011224423069506884, 1.6461060047149658 }, 1.031570072121367 },
	{ ( float[3] ) { 2.161475419998169, 0.019650086760520935, 1.1518051624298096 }, 0.2959790016116011 },
	{ ( float[3] ) { -0.2723003625869751, 2.3768131732940674, -0.08094538003206253 }, 0.4924115432873499 },
	{ ( float[3] ) { -0.12115160375833511, 3.1459529399871826, -0.35743948817253113 }, 0.8442269552943586 },
	{ ( float[3] ) { -0.5261813998222351, 0.14053885638713837, 0.08496662974357605 }, 0.4194560883851291 },
	{ ( float[3] ) { -0.34244564175605774, 0.5364210605621338, 0.000532335601747036 }, 0.4604166870447833 },
	{ ( float[3] ) { 1.4638875722885132, -0.4808245599269867, 0.34849992394447327 }, 0.6707417517848657 },
	{ ( float[3] ) { -0.594906210899353, 0.8710493445396423, 0.43262913823127747 }, 0.4724944898040495 },
	{ ( float[3] ) { 1.6608657836914062, 0.44450876116752625, -0.06339642405509949 }, 0.42846784462945287 },
	{ ( float[3] ) { 0.16685345768928528, 2.778691530227661, 0.9372642636299133 }, 0.43544084894807383 },
	{ ( float[3] ) { 1.0641510486602783, 2.6425113677978516, 0.7970979809761047 }, 0.6271655192287804 },
	{ ( float[3] ) { 0.30768105387687683, 1.7980595827102661, 2.729546546936035 }, 0.9890029493004413 },
	{ ( float[3] ) { 0.13079512119293213, 2.6247448921203613, 1.5065226554870605 }, 0.7232549204512918 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
