/*
 * Copyright (c) 2024 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 11, 22 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 4.598740245868833, 3.0765670669068275, 2.0936788450296744 };
const float ei_classifier_anom_mean[3] = { 4.124793295218616, 2.8621887842689953, 2.2566755305631605 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { -0.8936749696731567, -0.922140896320343, -1.058412790298462 }, 0.4502282479222878 },
	{ ( float[3] ) { -0.18241189420223236, 1.3848332166671753, -0.04795486852526665 }, 0.42830166461864994 },
	{ ( float[3] ) { -0.45192572474479675, -0.04482810199260712, 1.1468089818954468 }, 0.4786278107697267 },
	{ ( float[3] ) { -0.49883341789245605, -0.048002246767282486, 1.575413703918457 }, 0.8220194555834488 },
	{ ( float[3] ) { -0.3482969403266907, -0.38867369294166565, 2.108232259750366 }, 0.773278015208133 },
	{ ( float[3] ) { 1.831133246421814, 0.48588255047798157, 0.3797670304775238 }, 0.45974533606253704 },
	{ ( float[3] ) { -0.3004595935344696, -0.024957600980997086, 2.9065754413604736 }, 0.7151238501161129 },
	{ ( float[3] ) { 1.1567200422286987, -0.10969612747430801, -0.4102109372615814 }, 0.38317452515834355 },
	{ ( float[3] ) { 1.35161554813385, -0.39666053652763367, -0.32103782892227173 }, 0.40733495702658623 },
	{ ( float[3] ) { -0.6593718528747559, -0.41204047203063965, -0.6808229684829712 }, 0.38282178071602546 },
	{ ( float[3] ) { 2.127335786819458, -0.058768246322870255, 0.8321166634559631 }, 0.6353155248430178 },
	{ ( float[3] ) { 1.5398879051208496, -0.048671454191207886, -0.46884027123451233 }, 0.49418277821774315 },
	{ ( float[3] ) { 1.9978731870651245, 0.12611643970012665, 0.2527277171611786 }, 0.4288148269273768 },
	{ ( float[3] ) { -0.6091101169586182, -0.24582351744174957, -0.8143818974494934 }, 0.3410479674619727 },
	{ ( float[3] ) { 1.0778310298919678, -0.2204045206308365, 0.4685070514678955 }, 0.4439256567755259 },
	{ ( float[3] ) { -0.5044216513633728, 0.21497786045074463, -0.36051514744758606 }, 0.41374423924629383 },
	{ ( float[3] ) { -0.5922383666038513, -0.36527034640312195, 1.3635740280151367 }, 0.46562934381128634 },
	{ ( float[3] ) { -0.689568817615509, -0.5933825969696045, 0.9085448384284973 }, 0.5202182594413047 },
	{ ( float[3] ) { 0.036015499383211136, 0.5973157286643982, 0.6806363463401794 }, 0.7051988326935958 },
	{ ( float[3] ) { -0.15625694394111633, 2.0199451446533203, 0.5861085057258606 }, 0.5923043347536024 },
	{ ( float[3] ) { -0.25164300203323364, 2.3025894165039062, -0.022419726476073265 }, 0.45031654860517645 },
	{ ( float[3] ) { -0.39402177929878235, 0.11987817287445068, 2.1779401302337646 }, 1.0406575490171894 },
	{ ( float[3] ) { -0.26991844177246094, 2.9313976764678955, -0.40592721104621887 }, 0.4620838242890005 },
	{ ( float[3] ) { -0.5241362452507019, 0.14795993268489838, 0.0813307985663414 }, 0.42635226836240797 },
	{ ( float[3] ) { -0.33658966422080994, 0.5408389568328857, 0.007278477773070335 }, 0.4733587083892051 },
	{ ( float[3] ) { 1.463545322418213, -0.4895622134208679, 0.3306123614311218 }, 0.4583366285077409 },
	{ ( float[3] ) { -0.6082420945167542, 0.8714585304260254, 0.4365161657333374 }, 0.336178981178928 },
	{ ( float[3] ) { 1.600140929222107, 0.35312679409980774, -0.09565328061580658 }, 0.4560495350192522 },
	{ ( float[3] ) { 0.023918870836496353, 3.3287479877471924, -0.2869546711444855 }, 0.6382735446770751 },
	{ ( float[3] ) { 0.1495267152786255, 2.721025228500366, 1.1420072317123413 }, 0.6268969632425326 },
	{ ( float[3] ) { 1.0641510486602783, 2.6425113677978516, 0.7970980405807495 }, 0.6271655699445575 },
	{ ( float[3] ) { 0.3329426646232605, 1.990802526473999, 2.736426591873169 }, 0.866793398394665 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
