/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_43_4[] = { 0, 11, 22 };

// (before - mean) / scale
const float ei_classifier_anom_scale_43_4[3] = { 4.624091607017868, 3.087898029381507, 2.0612164195028755 };
const float ei_classifier_anom_mean_43_4[3] = { 4.130897597914873, 2.8558633318647297, 2.213898305068428 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_43_4[32] = {
	{ ( float[3] ) { -0.8898983001708984, -0.9161274433135986, -1.0529570579528809 }, 0.46178802274385977 },
	{ ( float[3] ) { 1.5642839670181274, -0.1921110451221466, -0.46868735551834106 }, 0.4123984149156099 },
	{ ( float[3] ) { -0.19094233214855194, 1.3942583799362183, -0.012681026943027973 }, 0.452961396030579 },
	{ ( float[3] ) { -0.6007692217826843, -0.35150718688964844, 1.3767626285552979 }, 0.30253000326712587 },
	{ ( float[3] ) { -0.38213294744491577, 0.4145375192165375, 0.04071913659572601 }, 0.6643316710185045 },
	{ ( float[3] ) { 2.1276297569274902, -0.05985517427325249, 0.6572050452232361 }, 0.3464999661644575 },
	{ ( float[3] ) { -0.5175719261169434, 0.035263996571302414, 1.6443073749542236 }, 0.478180563172133 },
	{ ( float[3] ) { -0.6019004583358765, -0.2427322268486023, -0.6669974327087402 }, 0.36492438755709916 },
	{ ( float[3] ) { -0.5097036361694336, 0.22486859560012817, -0.328828901052475 }, 0.4554845805189649 },
	{ ( float[3] ) { -0.39741241931915283, -0.26935499906539917, 2.3106229305267334 }, 0.4731916403097038 },
	{ ( float[3] ) { 0.03514494374394417, 0.5191561579704285, 0.7309054136276245 }, 0.4220203472785591 },
	{ ( float[3] ) { -0.6593450903892517, -0.400218665599823, -0.8169373273849487 }, 0.41708943069974663 },
	{ ( float[3] ) { 0.07593732327222824, 3.4107725620269775, -0.18327893316745758 }, 0.5112533891637868 },
	{ ( float[3] ) { -0.15841007232666016, 2.0251917839050293, 0.6268419027328491 }, 0.595576539108601 },
	{ ( float[3] ) { -0.42802828550338745, -0.05176660418510437, 1.218697190284729 }, 0.3963252846947768 },
	{ ( float[3] ) { 1.196765422821045, -0.3473822772502899, -0.3850095272064209 }, 0.46297036387336316 },
	{ ( float[3] ) { 1.9713261127471924, 0.1429063230752945, 0.21118168532848358 }, 0.44134435992708126 },
	{ ( float[3] ) { -0.2535530924797058, 2.304295063018799, -0.013449599035084248 }, 0.45531720610866855 },
	{ ( float[3] ) { -0.2142845243215561, 2.9909451007843018, -0.39911678433418274 }, 0.47796736170930715 },
	{ ( float[3] ) { -0.6892786026000977, -0.5819748640060425, 0.9270878434181213 }, 0.5131912291065083 },
	{ ( float[3] ) { 1.432356357574463, -0.4379853308200836, 0.08996573835611343 }, 0.4017097721751363 },
	{ ( float[3] ) { -0.47902119159698486, -0.3741627633571625, 1.7906932830810547 }, 0.41540784075773735 },
	{ ( float[3] ) { 1.8534793853759766, 0.4179951548576355, 0.45269811153411865 }, 0.43515528780271934 },
	{ ( float[3] ) { 2.1559386253356934, 0.01965620368719101, 1.2248797416687012 }, 0.29597202753755686 },
	{ ( float[3] ) { -0.30981940031051636, 0.013127678073942661, 3.0216140747070312 }, 0.46478541756823194 },
	{ ( float[3] ) { 1.6437407732009888, 0.49516943097114563, 0.00873511005192995 }, 0.36345878216886923 },
	{ ( float[3] ) { 1.3718898296356201, 0.08722226321697235, -0.30387139320373535 }, 0.40811581804050284 },
	{ ( float[3] ) { 0.15033666789531708, 2.7081987857818604, 1.1740241050720215 }, 0.6415763264490244 },
	{ ( float[3] ) { 1.0569968223571777, 2.6348633766174316, 0.8304049968719482 }, 0.6335547533045902 },
	{ ( float[3] ) { 1.1886143684387207, -0.2868526577949524, 0.5141638517379761 }, 0.6011054746985798 },
	{ ( float[3] ) { -0.5675193071365356, 0.8627400994300842, 0.43004119396209717 }, 0.3649780186633162 },
	{ ( float[3] ) { 0.3297972083091736, 1.9855458736419678, 2.800276517868042 }, 0.8766421479257634 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
